add_rules("mode.debug", "mode.release")
add_requires("imgui", {configs = {glfw_opengl3 = true}})
add_requires("stb")

target("main")
	set_kind("binary")
	add_defines("__STDC_LIMIT_MACROS")
	add_files("src/main.cc")
	add_packages("imgui", "stb")
	set_languages("c++23")
	set_encodings("utf-8")
	-- set_warnings("everything")
	set_rundir("$(projectdir)")
