add_repositories("xege-repo git@gitee.com:xege/ege-xrepo.git")
add_requires("xege 20.08")

target ("main")
	add_defines("__STDC_LIMIT_MACROS")
	add_packages("xege")
	set_kind ("binary")
	set_languages("c++2a")
	add_includedirs("$(projectdir)/3rd/microui-impl-ege")
	add_files ("$(projectdir)/main.cpp")
	add_files("$(projectdir)/3rd/microui-impl-ege/microui.c")
	add_files("$(projectdir)/3rd/microui-impl-ege/microui_impl_ege.cpp")
	set_warnings("everything")
	set_rundir("$(projectdir)")